### ISSUE TITLE
hi! Thank you for your excellent work! I would like to ask if the link of pre-extracted feature files of MSR-VTT is invalid, could you send it again? Thank you

### ISSUE THREAD

**Issue by xyc0833** [yangbang18/CLIP-Captioner#3]
hi! Thank you for your excellent work! I would like to ask if the link of pre-extracted feature files of MSR-VTT is invalid, could you send it again? Thank you

**Comment by myccver** [comment]
I meet the same problem

**Comment by yangbang18** [comment]
Hi, I have updated the link now. I have no idea why it expires after a period of time. I will find a new netdisk.

**Comment by myccver** [comment]
> Hi, I have updated the link now. I have no idea why it expires after a period of time. I will find a new netdisk.

Thank you, I am now able to download.
